Post_added
leomvit/leomvit.github.io pull request #125
Opened 2021-07-08 21:07 UTC by AdarshSingh223

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-07-08 21:27 UTC, AvikantSrivastava requested changes
Rest of the things look perfect, just make the changes that I have requested :)

2021-07-08 21:27 UTC, AvikantSrivastava commented on _pages/author-adarsh.html
> +permalink: "/author-adarsh-singh"
`permalink: "/author-adarsh-singh"` should match with the filename

## Changed that you can make 
1. Either make it `permalink: "/author-adarsh"` 
2. or change the filename to  `_pages/author-adarsh-singh.html`

2021-07-08 21:30 UTC, AvikantSrivastava commented
@AdarshSingh223 Also, while making a PR, don't work on the `master` branch of your cloned repo,
Always make a new branch (copy of the master branch) and makes changes to the new branch.

Later make a PR from the new branch.

This should be avoided
![image](https://user-images.githubusercontent.com/41926176/124993288-cb2b6380-e061-11eb-8a7e-83bef1486544.png)

2021-07-09 15:35 UTC, kaushikikrityy requested changes
The site link you should change! It belongs to someone else.

2021-07-09 15:37 UTC, kaushikikrityy requested changes
Your permalink is not working.

2021-07-09 15:38 UTC, kaushikikrityy reviewed
This is perfect!

2021-07-09 17:24 UTC, AdarshSingh223 commented
@kaushikikrityy @AvikantSrivastava I made the recommended changes.

2021-07-09 18:08 UTC, kaushikikrityy commented
@AdarshSingh223 The changes look perfect! @AvikantSrivastava please review!

2021-07-09 19:19 UTC, AvikantSrivastava requested changes

2021-07-09 19:19 UTC, AvikantSrivastava commented on Gemfile.lock
> -    addressable (2.7.0)
Please remove this file from the commit

2021-07-09 19:19 UTC, AvikantSrivastava commented on _config.yml
> +  adarsh:
Can you put you name in Alphabetical order?

2021-07-10 04:53 UTC, closed without merging